module.exports = {
  projects: [
    '<rootDir>/apps/individual-v2',
    '<rootDir>/apps/individual-modular',
    '<rootDir>/apps/uex-website',
    '<rootDir>/apps/backoffice',
    '<rootDir>/libs/uex-models',
    '<rootDir>/libs/uex-services',
    '<rootDir>/libs/uex-store',
    '<rootDir>/libs/uex-constants',
    '<rootDir>/libs/uex-popup',
    '<rootDir>/libs/uex-tel-input',
    '<rootDir>/libs/uex-browser-not-supported',
    '<rootDir>/libs/uex-breadcrumb',
    '<rootDir>/libs/uex-coverage-details',
    '<rootDir>/libs/uex-dark-menu',
    '<rootDir>/libs/uex-header',
    '<rootDir>/libs/uex-left-menu',
    '<rootDir>/libs/uex-offer-customisation',
    '<rootDir>/libs/uex-quote-summary',
    '<rootDir>/libs/uex-sidenav',
    '<rootDir>/libs/uex-snackbar',
    '<rootDir>/libs/uex-guards',
    '<rootDir>/libs/uex-resolvers',
    '<rootDir>/libs/uex-pipes',
  ],
};
